### PR TITLE
No need for separate commits for suburb+results

### PR DESCRIPTION
**Pull request by lyricnz**

### CODE REVIEW

**Comment by LukePrior** [comment]
I split it out so I could pull the repo before updating the results.json file because otherwise I run into conflicts if two or more actions are going at the same time.

**Comment by lyricnz** [comment]
Not sure I understand. How can that happen?  The two operations are kindof linked - as soon as you've updated/added a suburb file, the results.json is out of date...?

**Comment by LukePrior** [comment]
Say I start 2 jobs at 10am.

They both checkout the repo at the same time with the same results.json.

The first job finishes at 10:20 and successfully pushes an updated results.json.

The second job finishes at 10:25 but can't push results.json due to a conflict and fails.

**Comment by LukePrior** [comment]
By splitting it into 2 parts the chance of a conflict is greatly reduced, I suspect there is a better way to deal with it.

**Comment by LukePrior** [comment]
Now that all the results are stable this might be fine, will investigate

**Comment by LukePrior** [comment]
Resolved here: https://github.com/LukePrior/nbn-upgrade-map/commit/1e270f21d078417b31c9f289ea7fc0490e9a1a30

**Pull request closed without merging**
