### PR TITLE
Cleanup old APIs, and move result/progress update to main cycle

### PR DESCRIPTION
**Pull request by lyricnz**
- also, removing per-address progress (for now), including badges
- fix bug with explicit state/suburb args
- fix type hints `str|None`

### CODE REVIEW

**Comment by LukePrior** [comment]
While I would like to keep per-address progress if possible in such a way that doesn't need a recheck of every file, everything else looks good

**Comment by lyricnz** [comment]
Removed progress.json from the PR. The first run after merge will fix it.

**Comment by LukePrior** [comment]
Hmm linter not happy

**Comment by lyricnz** [comment]
I'll fix the linter.  And we can add address-progress back by adding counters to the top-level file.  Would like to do that in separate PR.

**Comment by LukePrior** [comment]
Ok

**Comment by LukePrior** [comment]
Alright merged in and restarted latest action, let's see how it goes

**Pull request merged**
