### PR TITLE
Feature/state breakdown

### PR DESCRIPTION
**Pull request by lyricnz**
Per https://github.com/LukePrior/nbn-upgrade-map/issues/333

eg: victoria (CSV loaded in spreadsheet and graphed)

image

It would be nice to support this render in stats.html with a state/national dropdown

### CODE REVIEW

**Comment by lyricnz** [comment]
@LukePrior this PR creates `results/breakdown-state.json` and `results/breakdown.$STATE.csv` - would you prefer `results/$STATE/breakdown.csv` for the latter?

**Comment by LukePrior** [comment]
Thanks for this,

I think in this case `results/breakdown.$STATE.csv` is fine for now, in future might move things to a breakdown folder.

**Comment by lyricnz** [comment]
I'll connect it to the update job, sec

**Comment by lyricnz** [comment]
I'll raise a new PR "someday" to make the stats.html use this data too...

**Comment by LukePrior** [comment]
I did a quick and dirty implementation just so it can be viewed:

https://github.com/LukePrior/nbn-upgrade-map/commit/0f95df3be3ea1c1bc774d3febd3ccd9a1124b742

https://lukeprior.github.io/nbn-upgrade-map/stats?region=NSW

**Comment by lyricnz** [comment]
@LukePrior I just had FTTP installed at my place, and was chatting to the contractors. They were super interested in the data from this project, hence the feature-request here.  Their particular interest was how much FTTN/FTTC/HFC -> FTTP work was left in Victoria, hence how much more work was available for them.  I write the PR above while they were digging :)

**Comment by lyricnz** [comment]
@LukePrior I suck at javascript, but attempted to add a dropdown for changing regions

https://github.com/LukePrior/nbn-upgrade-map/assets/122371/369d3612-6e66-46b0-b508-57534ff5e79b

https://github.com/LukePrior/nbn-upgrade-map/pull/336

**Pull request merged**
