### PR TITLE
Add basic historical view to the map

### PR DESCRIPTION
**Pull request by lyricnz**
Uses the github REST API for commits to the current suburb file, then adds a drop-down with all dates found. Seems to work OK.
- may fail if the data-format of old records is incompatible
- default_state default_suburub default_commit are being set in the handler, probably misusing them?
- I think there's still an issue with changing locations

https://github.com/LukePrior/nbn-upgrade-map/assets/122371/8253f9a0-8213-4478-ae49-bec797122e0b

### CODE REVIEW

**Comment by lyricnz** [comment]
https://github.com/LukePrior/nbn-upgrade-map/issues/288

**Comment by LukePrior** [comment]
Oh wow this is very cool, the date selector might be slightly misleading as it's just the latest data we had at or before that date.

But to have the correct dates for each individual suburb the summary file would be need to be large or somehow integrate the commit hashes into the geojson not sure.

**Comment by lyricnz** [comment]
I don't understand?  The date selector is the date at which the geojson file was updated and put into git (it uses the github history for the file to get a list of commits, and gets the dates from them - if you change suburbs, you get a different set of dates).  

ie: https://api.github.com/repos/LukePrior/nbn-upgrade-map/commits?path=results/VIC/somerville.geojson
Code uses `commit.sha` and `commit.commit.author.date`

**Comment by LukePrior** [comment]
Oh yes please disregard I only had a cursory look and saw the python function, this implementation looks good and should work well.

**Comment by lyricnz** [comment]
> Oh yes please disregard I only had a cursory look and saw the python function, this implementation looks good and should work well.

That was an experiment, I will remove those now.   I'm going to change the "Last Update" text to reflect the date selector too.

**Comment by lyricnz** [comment]
It would be good if someone else could test this - I don't want to break the website with some bad code.

TODO:
- make location of dropdowns predictable: the two dropdowns both happen asynchronously, and add elements `topright` which makes a race condition
- add "loading" message during async loads so UI doesn't look frozen or not updating
- maybe use a slider, rather than a dropdown, for the selector
- rename default_(state|suburb|commit) variable - this doesn't feel like a default now that we're updating it in loadSuburb()

**Comment by lyricnz** [comment]
https://github.com/LukePrior/nbn-upgrade-map/assets/122371/a774232a-97c1-4253-a55b-14fa78546909

**Comment by lyricnz** [comment]
PS: I'm not a frontend guy, excuse my ugly code.

**Comment by LukePrior** [comment]
The basis of this site is my rushed code, this looks fine and is a great addition.

I would ideally like to remake it at somepoint in the future but that is a long ways off.

Will do some testing locally and if everything checks out merge it in later.

**Comment by LukePrior** [comment]
I'm not sure about the "latest suburb" entry which has the same affect as the option immediately preceding it, could cause confusion might be best just to remove it.

**Comment by lyricnz** [comment]
Ah yes, I'd already removed it, just not pushed. Will do now.

**Comment by blonghong** [comment]
This is perfect! Thank you so much for implementing this so quickly.

**Pull request merged**
