### PR TITLE
Dockerfile and README.md for building an image

### PR DESCRIPTION
**Pull request by lyricnz**
```shell
❯ docker build . -f extra/docker/Dockerfile -t nbn-upgrade-map:latest

[+] Building 18.2s (10/10) FINISHED                                                                                                                                                                              docker:desktop-linux
...

❯ docker run -it -v ./results:/app/results --network test_network nbn-upgrade-map:latest ./main.py -H db -P 5432

2023-09-15 04:38:57,336 INFO MainThread Creating DB index...
2023-09-15 04:38:57,436 INFO MainThread Checking for unprocessed suburbs...
2023-09-15 04:38:57,436 INFO MainThread Checking for announced suburbs that haven't been updated in 21 days...
2023-09-15 04:38:57,437 INFO MainThread Checking for all suburbs...
2023-09-15 04:38:57,447 INFO MainThread Processing Southern Cross, VIC
2023-09-15 04:38:57,447 INFO MainThread Fetching all addresses for Southern Cross, VIC
2023-09-15 04:38:57,486 INFO MainThread Fetched 53 addresses from database
2023-09-15 04:38:57,493 INFO MainThread Loaded 52 addresses from output file
2023-09-15 04:38:57,493 INFO MainThread Submitting 53 requests to add NBNco data...
2023-09-15 04:39:15,815 INFO nbn_0 Completed 53 requests
2023-09-15 04:39:15,822 INFO MainThread Completed. Tally of tech types: {'WIRELESS': 53}
2023-09-15 04:39:15,822 INFO MainThread Location ID types: {'LOC': 47, 'Other': 6}
2023-09-15 04:39:15,825 INFO MainThread Writing results to results/VIC/southern-cross.geojson
2023-09-15 04:39:17,004 INFO MainThread Updating progress.json
```

### CODE REVIEW

**Comment by lyricnz** [comment]
Per https://github.com/LukePrior/nbn-upgrade-map/issues/250

**Comment by lyricnz** [comment]
Will make GHA to build and publish the image...

**Comment by LukePrior** [comment]
Excellent, thanks for this.

Could potentially save a bit of extra time on the action by not [checking out the results](https://github.com/LukePrior/nbn-upgrade-map/blob/main/.github/workflows/codeql.yml#L35C5-L35C5) but I think unless it becomes necessary, it should be fine.

**Comment by lyricnz** [comment]
I might do the sparse checkout, just for efficiency; and I can then remove the Maximise Build Space step too, which takes >1 minute.  I'm just experimenting with a docker-compose file here too...

**Comment by LukePrior** [comment]
https://hub.docker.com/repository/docker/lukeprior/nbn-upgrade-map/general

**Pull request merged**
