### PR TITLE
Replace multiple json files in results with a richer format

### PR DESCRIPTION
**Pull request by lyricnz**
To address #135 

Also adds tools to address #137 and #139

### CODE REVIEW

**Comment by lyricnz** [comment]
This PR is getting too big (too hard to review; open too long), and doesn't yet change anything about the output.  Added lots of framework, will consolidate the files in subsequent PR.

**Comment by lyricnz** [comment]
Suggest hide whitespace, and ignore code/adhoc_tools.py, and the new dataclass for Suburbs (not used yet)

https://github.com/LukePrior/nbn-upgrade-map/pull/140/files?diff=unified&w=1

**Comment by LukePrior** [comment]
Ok yeah,

Lots of changes but on first look everything seems fine, I'm not currently at my development machine so can't test locally.

But yeah it's a great framework to build from so LGTM.

**Comment by LukePrior** [comment]
https://github.com/LukePrior/nbn-upgrade-map/issues/144

**Pull request merged**
