### PR TITLE
Mechanism for creating a much smaller DB

### PR DESCRIPTION
**Pull request by lyricnz**
https://github.com/LukePrior/nbn-upgrade-map/issues/98

```
❯ docker images
REPOSITORY           TAG       IMAGE ID       CREATED         SIZE
mydb                 latest    84af660a3493   8 minutes ago   3.73GB
minus34/gnafloader   latest    d2c552c72a0a   10 days ago     32GB
```

### CODE REVIEW

**Comment by lyricnz** [comment]
Maybe image should be pushed somewhere, and used in GHA?

**Comment by LukePrior** [comment]
Yeah it would be good to get it on Docker Hub.

I don't know if it should be contained within this repo, main concern is it's increasing the amount of maintaince required incase of changes.

Maybe a new repo for it or see if the original creator would be open to offering a slim version like this.

**Comment by lyricnz** [comment]
The reason I put it in this repo is that the data is 100% aligned to this tool. Frankly, I have trouble running the upstream docker container - it's so big, and I don't have a lot of space in my docker VM.

**Comment by LukePrior** [comment]
Oh yeah that makes sense, well I'll merge it in and we can investigate getting it hosted somewhere/switching GHA over to using it.

**Comment by lyricnz** [comment]
The reduced image size will save ~90% of the ~6.5 minutes that GHA takes to pull the image. The new image would also run the DB query faster because the query index is built-in.

```
2023-06-02T03:57:19.9813499Z 2023-06-02 03:57:19,981 INFO Fetching all addresses for Narrabri, NSW
2023-06-02T03:58:34.1744133Z 2023-06-02 03:58:34,173 INFO Fetched 5175 addresses from database
```

**Pull request merged**
