### PR TITLE
Add support for using  SQLite as a DB

### PR DESCRIPTION
**Pull request by lyricnz**
Related to https://github.com/LukePrior/nbn-upgrade-map/issues/268
- removes need for docker for local development/execution (once you have the DB file)
- removes need for 3GB docker image
- removes need for cpu + memory required to run postgres in docker

Future work:
- publish the DB image somewhere; Perhaps using [Git LFS](https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage)
- compress?
- read-only?
- automatic bootstrap if DB file not found (download, unpack etc)
- web-based DB file, using range HTTP requests?

### CODE REVIEW

**Comment by lyricnz** [comment]
Experimenting with LFS for the (whole) DB file.

If someone attempts checkout without git-lfs installed, they'll just get a pointer to the file
https://docs.github.com/en/repositories/working-with-files/managing-large-files/collaboration-with-git-large-file-storage

**Comment by lyricnz** [comment]
PR also removes db.get_list_vs_total() which wasn't used anyway

**Comment by lyricnz** [comment]
Sample releases (from my fork): https://github.com/lyricnz/nbn-upgrade-map/releases

**Comment by lyricnz** [comment]
So @LukePrior ?

**Comment by LukePrior** [comment]
Looks good

**Pull request merged**
