### PR TITLE
Kludge to handle FW->FTTN upgrades

### PR DESCRIPTION
**Pull request by lyricnz**
Per https://github.com/LukePrior/nbn-upgrade-map/issues/350

Added local variable `address_detail` to simplify code a little.

### CODE REVIEW

**Comment by LukePrior** [comment]
Does the frontend need any work to display this correctly?

**Comment by lyricnz** [comment]
> Does the frontend need any work to display this correctly?

It shouldn't do - some addresses will now show up as tech=FW and upgrade=FTTN_SA.  The javascript will render the FW address as #C91414 red, and the popup should show the upgrade as FTTN_SA, but it won't show as an upgrade by node colour.

https://github.com/lyricnz/nbn-upgrade-map/blob/feature/fw-to-fttn-upgrade-kludge/site/main.js#L161

How would you want to show this?

**Comment by LukePrior** [comment]
Ahh ok cool, that should be fine, in future I would like to make the legend dynamic so it only shows for technologies actually present in that suburb but that's a future seperate job.

**Comment by lyricnz** [comment]
Looks like they show up black. I didn't even know that was a thing :)

image

**Comment by lyricnz** [comment]
https://github.com/LukePrior/nbn-upgrade-map/blob/main/site/main.js#L161

```python
    // This should never happen
    return "#000000";
```

**Comment by lyricnz** [comment]
I guess it doesn't say that tech-change is to FTTN, not FTTP...

**Comment by LukePrior** [comment]
I think this is responsible for https://github.com/LukePrior/nbn-upgrade-map/issues/354

**Pull request merged**
