### PR TITLE
Implement weekly breakdown CI job 

### PR DESCRIPTION
**Pull request by lyricnz**
Per https://github.com/LukePrior/nbn-upgrade-map/issues/265

### CODE REVIEW

**Comment by LukePrior** [comment]
Will this throw off the weekly data with GHA cron not lining up with existing weekly records?

**Comment by lyricnz** [comment]
"weekly" is just how the seed script did it.  The date is whatever it says in the json (should be plotted as XY, not assuming linear time axis).  If that's too hard, it could be moved to ~Tuesday (depending on timezones).

**Comment by LukePrior** [comment]
I don't think it currently handles time properly, but it would be an easy enough fix more just the perfectionist in me wanting a week gap always.

**Comment by lyricnz** [comment]
FWIW, I haven't figured out how it works with timezones. Currently the last sample is 2023-09-19, which would mean the next is 26th (Tuesday).  Google tells me github is UTC. 

Changed GHA to 01:00 every Tuesday

**Comment by LukePrior** [comment]
tyvm

**Pull request merged**
