### PR TITLE
Some unit-tests for nbn-upgrade-map using pytest

### PR DESCRIPTION
**Pull request by lyricnz**
Per https://github.com/LukePrior/nbn-upgrade-map/issues/89

### CODE REVIEW

**Comment by lyricnz** [comment]
Working on improving coverage now

```
Name                  Stmts   Miss  Cover
-----------------------------------------
code/adhoc_tools.py     114    114     0%
code/data.py             32      3    91%
code/db.py               62     48    23%
code/geojson.py          31     12    61%
code/main.py            132     85    36%
code/nbn.py              45     28    38%
code/suburbs.py          89     37    58%
code/utils.py            14      6    57%
-----------------------------------------
TOTAL                   519    333    36%
```

**Comment by lyricnz** [comment]
```
❯ PYTHONPATH=code pytest tests --cov=code
======================================================================== test session starts =========================================================================
platform darwin -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0
rootdir: /Users/simonroberts/src/github/lyricnz/nbn-upgrade-map
plugins: cov-4.1.0
collected 9 items

tests/test_combined_suburbs.py ....                                                                                                                            [ 44%]
tests/test_geojson.py ...                                                                                                                                      [ 77%]
tests/test_utils.py .s                                                                                                                                         [100%]

--------- coverage: platform darwin, python 3.10.12-final-0 ----------
Name                  Stmts   Miss  Cover
-----------------------------------------
code/adhoc_tools.py     114    114     0%
code/data.py             32      0   100%
code/db.py               62     48    23%
code/geojson.py          33      0   100%
code/main.py            132     79    40%
code/nbn.py              45     28    38%
code/suburbs.py          89     37    58%
code/utils.py            14      6    57%
-----------------------------------------
TOTAL                   521    312    40%
```

**Comment by lyricnz** [comment]
```


Module | statements | missing | excluded | coverage
-- | -- | -- | -- | --
code/adhoc_tools.py | 114 | 114 | 0 | 0%
code/data.py | 32 | 0 | 0 | 100%
code/db.py | 62 | 48 | 0 | 23%
code/geojson.py | 33 | 0 | 0 | 100%
code/main.py | 132 | 68 | 0 | 48%
code/nbn.py | 45 | 19 | 0 | 58%
code/suburbs.py | 89 | 25 | 0 | 72%
code/utils.py | 14 | 0 | 0 | 100%
Total | 521 | 274 | 0 | 47%

Module	statements	missing	excluded	coverage
[code/adhoc_tools.py](https://github.com/LukePrior/nbn-upgrade-map/pull/d_1c76e98fcac0e60a_adhoc_tools_py.html)	114	114	0	0%
[code/data.py](https://github.com/LukePrior/nbn-upgrade-map/pull/d_1c76e98fcac0e60a_data_py.html)	32	0	0	100%
[code/db.py](https://github.com/LukePrior/nbn-upgrade-map/pull/d_1c76e98fcac0e60a_db_py.html)	62	48	0	23%
[code/geojson.py](https://github.com/LukePrior/nbn-upgrade-map/pull/d_1c76e98fcac0e60a_geojson_py.html)	33	0	0	100%
[code/main.py](https://github.com/LukePrior/nbn-upgrade-map/pull/d_1c76e98fcac0e60a_main_py.html)	132	68	0	48%
[code/nbn.py](https://github.com/LukePrior/nbn-upgrade-map/pull/d_1c76e98fcac0e60a_nbn_py.html)	45	19	0	58%
[code/suburbs.py](https://github.com/LukePrior/nbn-upgrade-map/pull/d_1c76e98fcac0e60a_suburbs_py.html)	89	25	0	72%
[code/utils.py](https://github.com/LukePrior/nbn-upgrade-map/pull/d_1c76e98fcac0e60a_utils_py.html)	14	0	0	100%
Total	521	274	0	47%
```

**Comment by lyricnz** [comment]
```
Name                  Stmts   Miss  Cover
-----------------------------------------
code/adhoc_tools.py     114    114     0%
code/data.py             32      0   100%
code/db.py               62     48    23%
code/geojson.py          33      0   100%
code/main.py            132     68    48%
code/nbn.py              45      9    80%
code/suburbs.py          89      0   100%
code/utils.py            14      0   100%
-----------------------------------------
TOTAL                   521    239    54%
```

OK, I'm bored of writing unit tests now. Please review.

**Comment by LukePrior** [comment]
Wow this looks great, the tests all look good just those few comments about the GitHub Action.

**Comment by lyricnz** [comment]
The GHA is pretty much copied from https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

**Comment by lyricnz** [comment]
> those few comments about the GitHub Action.

Which comments?

**Comment by LukePrior** [comment]
> Which comments?

I did a review on GitHub maybe it isn't showing:
- for the paths the two `site/**` can be removed as there won't be any python code in that directory
- we don't need to check using both python 3.10 and 3.11, just 3.10 should be fine as that's the target?

**Comment by lyricnz** [comment]
1. I was allowing the possibility that the python code consumed html/js from that directory.  Can remove if you want.
2. I was adding 3.11 for "forward compatibility", so when the time comes, code will be ready

**Comment by LukePrior** [comment]
Alright then that should all be fine

**Pull request merged**
