### PR TITLE
Add cache for NBNco queries

### PR DESCRIPTION
**Pull request by lyricnz**
Per https://github.com/LukePrior/nbn-upgrade-map/issues/36

Add optional (default disabled) HTTP cache.
Split NBN access into separate functions.
Log exceptions that happen in the pooled executor.

### CODE REVIEW

**Comment by lyricnz** [comment]
HTTP cache is probably not the best solution.  Caching GNAF ID => LocID, and LocId => status directly would be more storage-efficient.

**Comment by LukePrior** [comment]
This looks good, if you don't plan to make any further changes I'm happy to merge it in or can leave it open

**Comment by lyricnz** [comment]
If you're OK with it, happy to merge. I changed the title to be more accurate.

**Comment by lyricnz** [comment]
FWIW although the two logical caches (GNAF ID => LocID, and LocId => status) are stored in the same physical cache, they don't overlap because the GNAF IDs all start with a unique prefix

**Pull request merged**
