### PR TITLE
Fix tech/upgrade for other _CT case (besides FW/WIRELESS)

### PR DESCRIPTION
**Pull request by lyricnz**
Per https://github.com/LukePrior/nbn-upgrade-map/issues/327

Generalise the FW_CT case for other tech types
Add tool to retrospectively fixup all the _CT tech types

### CODE REVIEW

**Comment by lyricnz** [comment]
After processing one state, this will impact the "upgrade" breakdown thusly (a bunch of rows removed):

| date       |   NULL_NA |   FTTP_SA |   FTTP_NA |   FTTN_CT |   FW_CT |   UNKNOWN |   FTTN_NA |   FTTC_NA |   SAT_CT |   FW_NA |   FTTC_CT |   FTTB_NA |   FTTN_SA |   FTTP |
|------------|-----------|-----------|-----------|-----------|---------|-----------|-----------|-----------|----------|---------|-----------|-----------|-----------|--------|
| 2024-04-30 |   5377677 |   2357200 |   2315829 |       484 |    1566 |      1781 |           |           |     4616 |      12 |         1 |           |           |        |
| 2024-05-07 |   5387683 |   2349476 |   2308656 |       414 |    1558 |      1796 |           |           |     4593 |       7 |         1 |           |           |        |
| 2024-05-14 |   5451217 |   2347995 |   2235904 |       284 |    1414 |      1778 |           |           |     4558 |       6 |           |           |       133 |        |
| 2024-05-17 |   5450743 |   2337390 |   2227809 |       112 |    1367 |      1769 |           |           |     4542 |       6 |           |           |       179 |    712 |

**Comment by lyricnz** [comment]
Latest breakdown.json record will be
```
    "2024-05-17": {
        "tech": {
            "FTTN": 4006479,
            "FTTP": 3005325,
            "HFC": 2735322,
            "FTTC": 1512383,
            "WIRELESS": 748805,
            "FTTB": 611251,
            "SATELLITE": 402411,
            "NULL": 175096
        },
        "upgrade": {
            "NULL_NA": 5450743,
            "FTTP_SA": 2337391,
            "FTTP_NA": 2227809,
            "FTTP": 167829,
            "WIRELESS": 4526,
            "UNKNOWN": 1769,
            "FTTC": 1181,
            "FTTN": 310,
            "FTTN_SA": 179,
            "FW_NA": 6,
            "SATELLITE": 3,
            "NULL": 1
        }
    }

```

**Comment by lyricnz** [comment]
If we want to fix all the current _CT addresses, we should stop the auto-processing, run fix_ct_upgrades(), commit and merge the change, before resuming the auto-processing. @LukePrior

**Comment by lyricnz** [comment]
Or at least merge this PR so the processing does it in the new way, then merge the retrofix.

**Comment by LukePrior** [comment]
Ok I've paused processing for now and will merge this PR.

**Comment by lyricnz** [comment]
Will run the script now, then PR the fixup

**Pull request merged**
